### ISSUE TITLE
Write rough Timeline for each week

### ISSUE THREAD

**Issue by 23958495** [CITS5206-Group5/Project#7]
Specify the milestones per week that the team agrees to work on.

**Comment by 23958495** [comment]
- Week 1: Project Kickoff
Establish goals, define scope, and assemble the project team.
- Weeks 2 - 3: Planning and Design Phase
Develop the project plan, establish a timeline, and allocate resources.
Initiate design work, review, and finalize project specifications.
- Week 4: Development Begins
Commence the development process and set up the development environment.
First Deliverable: WebAdmin Module, User Management, and HomePage.
- Week 5: Development Continues
Second Deliverable: Booking Management System.
Complete Sprint 1.
- Week 6: Development Progresses
Third Deliverable: Content Management System.
- Week 7: Development Advances
Fourth Deliverable: Chat Management System.
Complete Sprint 2.
- Week 8-9: Testing, Review, and Launch
Conduct testing and revisions.
Perform the final review.
Launch the project and close the MVP phase with training and documentation delivery.

**Comment by ktagintsev** [comment]
Looks good!
